In [1]:
import numpy as np

In [2]:
arr = np.arange(1, 11)

In [3]:
reshaped_arr = arr.reshape(2, 5)

In [4]:
print(reshaped_arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [5]:
import numpy as np

In [6]:
arr = np.arange(1, 21)

In [7]:
extracted = arr[5:15]

In [8]:
print(extracted)

[ 6  7  8  9 10 11 12 13 14 15]


In [9]:
import pandas as pd

In [10]:
fruit_series = pd.Series({'apples': 3, 'bananas': 2, 'oranges': 1})

In [11]:
fruit_series['pears'] = 4

In [12]:
print(fruit_series)

apples     3
bananas    2
oranges    1
pears      4
dtype: int64


In [13]:
import pandas as pd

In [14]:
data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace', 'Hannah', 'Ian', 'Jane'],
    'age': [25, 30, 35, 40, 22, 28, 33, 38, 27, 26],
    'gender': ['F', 'M', 'M', 'M', 'F', 'M', 'F', 'F', 'M', 'F']
}

In [15]:
df = pd.DataFrame(data)

In [16]:

print(df)

      name  age gender
0    Alice   25      F
1      Bob   30      M
2  Charlie   35      M
3    David   40      M
4      Eva   22      F
5    Frank   28      M
6    Grace   33      F
7   Hannah   38      F
8      Ian   27      M
9     Jane   26      F


In [17]:
import pandas as pd

In [18]:
occupations = ['Programmer', 'Manager', 'Analyst']

In [19]:
df['occupation'] = occupations * (len(df) // len(occupations)) + occupations[:len(df) % len(occupations)]

In [20]:
print(df)

      name  age gender  occupation
0    Alice   25      F  Programmer
1      Bob   30      M     Manager
2  Charlie   35      M     Analyst
3    David   40      M  Programmer
4      Eva   22      F     Manager
5    Frank   28      M     Analyst
6    Grace   33      F  Programmer
7   Hannah   38      F     Manager
8      Ian   27      M     Analyst
9     Jane   26      F  Programmer


In [21]:
filtered_df = df[df['age'] >= 30]

In [22]:
print(filtered_df)

      name  age gender  occupation
1      Bob   30      M     Manager
2  Charlie   35      M     Analyst
3    David   40      M  Programmer
6    Grace   33      F  Programmer
7   Hannah   38      F     Manager


In [23]:
df.to_csv('data.csv', index=False)

In [24]:
new_df = pd.read_csv('data.csv')

In [25]:
print(new_df)

      name  age gender  occupation
0    Alice   25      F  Programmer
1      Bob   30      M     Manager
2  Charlie   35      M     Analyst
3    David   40      M  Programmer
4      Eva   22      F     Manager
5    Frank   28      M     Analyst
6    Grace   33      F  Programmer
7   Hannah   38      F     Manager
8      Ian   27      M     Analyst
9     Jane   26      F  Programmer
